name: CI

env:
  RACK_ENV: 'test'

on:
  push:
    branches: [ master ]
  pull_request:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master
      - name: Install Ruby
        uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.7'
      - name: ruby version
        run: |
          ruby -v
